### PR TITLE
Add pgguclifetimes

### PR DESCRIPTION
**Pull request by tristan957**
pgguclifetimes is a standalone test program that finds variable declarations without lifetime annotations.

```shell
$ pgguclifetimes $builddir
# ...
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:61:16: Mode is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:61:16: Mode is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:63:27: MyBackendType is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:66:14: lock_files is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:66:14: lock_files is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:68:14: LocalLatchData is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:68:14: LocalLatchData is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:489:26: AuthenticatedUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:490:26: SessionUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:491:26: OuterUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:492:26: CurrentUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:493:34: SystemUser is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:499:26: SecurityRestrictionContext is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1014:22: MyClientConnectionInfo is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1014:22: MyClientConnectionInfo is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1777:10: session_preload_libraries_string is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1777:10: session_preload_libraries_string is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1778:10: shared_preload_libraries_string is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1778:10: shared_preload_libraries_string is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1779:10: local_preload_libraries_string is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1779:10: local_preload_libraries_string is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1785:25: shmem_request_hook is not marked as thread-local storage
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1785:25: shmem_request_hook is missing a lifetime annotation
# ...
```

Output is subject to change based on feedback. Right now I print two errors per missing annotation, but perhaps that is superfluous. You'll notice that the GUCs don't have errors associated with them even though they aren't annotated. This is because GUCs are already annotated in the GUC tables where they are defined.

### CODE REVIEW

**Comment by tristan957** [comment]
Not sure what to do about CI for right now given that libclang is not in the images.

**Comment by tristan957** [comment]
> You'll notice that the GUCs don't have errors associated with them even though they aren't annotated. This is because GUCs are already annotated in the GUC tables where they are defined.

Hmm. Not working as intended. Looking into it

**Comment by tristan957** [comment]
I think it is because this branch is old. Do you think we should rebase it? `GUC_ADDR` no longer exists.

**Comment by tristan957** [comment]
```
$ ./build/src/tools/pgguclifetimes/pgguclifetimes build/ src/backend/utils/init/miscinit.c 
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:61:16: Mode is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:63:27: MyBackendType is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:66:14: lock_files is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:68:14: LocalLatchData is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:489:26: AuthenticatedUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:490:26: SessionUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:491:26: OuterUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:492:26: CurrentUserId is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:493:34: SystemUser is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:499:26: SecurityRestrictionContext is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1014:22: MyClientConnectionInfo is missing a lifetime annotation
/home/tristan957/Projects/work/postgresql/src/backend/utils/init/miscinit.c:1785:25: shmem_request_hook is missing a lifetime annotation
```

Now it is working with this branch given the changes in the second commit.

**Comment by hlinnaka** [comment]
I rebased my  'threading'  branch over PostgreSQL master, then I rebased this over that. So this is all in the 'threading' branch now

**Pull request closed without merging**
